let quraa = [
    { id: 1, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/1.jpg', Audiosource: "https://download.ourquraan.com/Abu_Baker_Shatri/", title: "أبو بكر الشاطري" },
    { id: 2, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/2.jpg', Audiosource: "https://download.ourquraan.com/Ahmad_Al-Hawashy/", title: "أحمد الحواشي" },
    { id: 3, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/3.jpg', Audiosource: "https://download.ourquraan.com/Ahmed-Trabolsi(Hafs)/", title: "أحمد الطرابلسي" },
    { id: 4, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/4.jpg', Audiosource: "https://download.ourquraan.com/Ahmed_Alajmi/", title: "أحمد بن على العجمى" },
    { id: 5, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/5.jpg', Audiosource: "https://download.ourquraan.com/Ahmed_Saber/", title: "أحمد صابر" },
    { id: 6, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/6.jpg', Audiosource: "https://download.ourquraan.com/Ahmed-aamer/", title: "أحمد عامر" },
    { id: 7, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/7.jpg', Audiosource: "https://download.ourquraan.com/Ahmed_Mohamed_Salama/", title: "أحمد محمد سلامه" },
    { id: 8, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/8.jpg', Audiosource: "https://download.ourquraan.com/Ahmad_Nauina/", title: "أحمد نعينع" },
    { id: 9, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/9.jpg', Audiosource: 'https://download.ourquraan.com/Akram_Alalaqmi/', title: "أكرم العلاقمي" },
    { id: 10, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/10.jpg', Audiosource: 'https://download.ourquraan.com/Ibrahim_Alakhdar/', title: "إبراهيم الأخضر" },
    { id: 11, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/11.jpg', Audiosource: 'https://download.ourquraan.com/Ibrahim-algarmi/', title: "ابراهيم الجرمي" },
    { id: 12, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/12.jpg', Audiosource: 'https://download.ourquraan.com/Ibrahim-Aldosry(Warsh)/', title: "ابراهيم الدوسري" },
    { id: 13, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/13.jpg', Audiosource: 'https://download.ourquraan.com/Edres-Abkar/', title: "إدريس أبكر" },
    { id: 14, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/14.jpg', Audiosource: 'https://download.ourquraan.com/Ibrahim-Jamal-Alqerjawi-Hafs-An-Assem/', title: "ابراهيم جمال القرجاوي" },
    { id: 15, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/15.jpg', Audiosource: 'https://download.ourquraan.com/Al-dokali-mohamed(Qualon)/', title: "الدوكالي محمد العالم" },
    { id: 16, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/16.jpg', Audiosource: 'https://download.ourquraan.com/Alzain_Mohammad_Ahmad/', title: "الزين محمد أحمد" },
    { id: 17, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/17.jpg', Audiosource: 'https://download.ourquraan.com/Sodais_And_Shuraim/', title: "السديس والشريم" },
    { id: 18, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/18.jpg', Audiosource: 'https://download.ourquraan.com/Alashri_Omran/', title: "العشري عمران" },
    { id: 19, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/19.jpg', Audiosource: 'https://download.ourquraan.com/Aleyoon_Alkoshi_(Warsh)/', title: "العيون الكوشي" },
    { id: 20, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/20.jpg', Audiosource: 'https://download.ourquraan.com/Alfateh-mohamed(Aldory-3n-abi%20amr)/', title: "الفاتح محمد الزبير" },
    { id: 21, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/21.jpg', Audiosource: 'https://download.ourquraan.com/3bdul-bary_Mohammad/', title: "عبدالبارئ محمد" },
    { id: 22, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/22.jpg', Audiosource: 'https://download.ourquraan.com/Emad-Almansary/', title: "عماد المنصري" },
    { id: 23, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/23.jpg', Audiosource: 'https://download.ourquraan.com/Bander_Baleelah/', title: "بندر بليلة" },
    { id: 24, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/24.jpg', Audiosource: 'https://download.ourquraan.com/Tawfeeq_As-Sayegh/', title: "توفيق الصايغ" },
    { id: 25, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/25.jpg', Audiosource: 'https://download.ourquraan.com/Jamal_Shaker_Abdullah/', title: "جمال شاكر عبدالله" },
    { id: 26, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/26.png', Audiosource: 'https://download.ourquraan.com/Gom3an-Al3semy/', title: "جمعان العصيمي" },
    { id: 27, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/27.jpg', Audiosource: 'https://server16.mp3quran.net/h_saleh/Rewayat-Hafs-A-n-Assem/', title: "حسن صالح" },
    { id: 28, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/28.jpg', Audiosource: 'https://download.ourquraan.com/Hamad_Sinan/', title: "حمد سنان" },
    { id: 29, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/29.jpg', Audiosource: 'https://download.ourquraan.com/Khalid_Galil/', title: "خالد الجليل" },
    { id: 30, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/30.jpg', Audiosource: 'https://download.ourquraan.com/Khalid_Alqahtani/', title: "خالد القحطاني" },
    { id: 31, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/31.jpg', Audiosource: 'https://download.ourquraan.com/Khalid_Almohana/', title: "خالد المهنا" },
    { id: 32, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/32.jpg', Audiosource: 'https://download.ourquraan.com/Khalid_Abdulkhafi/', title: "خالد عبدالكافي" },
    { id: 33, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/33.jpg', Audiosource: 'https://download.ourquraan.com/Khalifah_At-Tonaeijy/', title: "خليفة الطنيجي" },
    { id: 34, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/34.jpg', Audiosource: 'https://download.ourquraan.com/Zaki_Daghistani/', title: "زكي داغستاني" },
    { id: 35, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/35.jpg', Audiosource: 'https://download.ourquraan.com/Saad_Alghamdi/', title: "سعد الغامدي" },
    { id: 36, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/36.jpg', Audiosource: 'https://download.ourquraan.com/Saud_Al-Shuraim/', title: "سعود الشريم"},
    { id: 37, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/37.jpg', Audiosource: 'https://download.ourquraan.com/Sahl_Yaaseen/', title: "سهل ياسين"},
    { id: 38, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/38.jpg', Audiosource: 'https://download.ourquraan.com/Sayeed_Ramadan/', title: "سيد رمضان"  },
    { id: 39, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/39.jpg', Audiosource: 'https://download.ourquraan.com/Shirazad_Taher/',title: "شيرزاد عبدالرحمن طاهر" },
    { id: 40, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/40.jpg', Audiosource: 'https://download.ourquraan.com/Saber_abdulhakm/', title: "صابر عبدالحكم"},
    { id: 41, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/41.jpg', Audiosource: 'https://download.ourquraan.com/Salah_Bukatir/', title: "صلاح بو خاطر" },
    { id: 42, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/42.jpg', Audiosource: 'https://download.ourquraan.com/Tarek-Abdalghany-Da3ob/', title: "طارق عبدالغني دعوب"},
    { id: 43, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/43.jpg', Audiosource: 'https://download.ourquraan.com/3adel_Alkalbani/', title: "عادل الكلباني" },
    { id: 44, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/44.jpg', Audiosource: 'https://download.ourquraan.com/3adel-Rayan/',  title: "عادل ريان" },
    { id: 45, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/45.jpg', Audiosource: 'https://download.ourquraan.com/3del_Muslim/', title: "عادل مسلم"},
    { id: 46, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/46.jpg', Audiosource: 'https://download.ourquraan.com/3bdalrahman_al3osy/', title: "عبد الرحمن العوسي"},
    { id: 47, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/47.jpg', Audiosource: 'https://download.ourquraan.com/3bdulRazaq_AlDulaimi-Mujawwad/',title: "عبد الرزاق الدليمي" },
    { id: 48, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/48.jpg', Audiosource: 'https://download.ourquraan.com/3bdul_Munem_Abdul_Mobdi/',  title: "عبد المنعم عبد المبدئ" },
    { id: 49, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/49.jpg', Audiosource: 'https://download.ourquraan.com/3bdulbari_Ath-Thubaity/', title: "عبدالبارئ الثبيتي" },
    { id: 50, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/50.jpg', Audiosource: 'https://download.ourquraan.com/3bdulbasit_Abdulsamad/', title: "عبدالباسط عبدالصمد" },
    { id: 51, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/51.jpg', Audiosource: 'https://download.ourquraan.com/3bdulrahman_Alsudais/',  title: "عبدالرحمن السديس" },
    { id: 52, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/52.jpg', Audiosource: 'https://download.ourquraan.com/3bdurRashid_Sufi_(Hafs%20An%20Assem)/', title: "عبدالرشيد صوفي"  },
    { id: 53, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/53.jpg', Audiosource: 'https://download.ourquraan.com/3bdulaziz_Alahmad/',  title: "عبدالعزيز الأحمد" },
    { id: 54, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/54.jpg', Audiosource: 'https://download.ourquraan.com/3bdallah_alkndry/', title: "عبدالله الكندري" },
    { id: 55, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/55.jpg', Audiosource: 'https://download.ourquraan.com/3bdallah_almatroud/', title: "عبدالله المطرود" },
    { id: 56, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/56.jpg', Audiosource: 'https://download.ourquraan.com/3bdullah_Basfer/', title: "عبدالله بصفر" },
    { id: 57, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/57.jpg', Audiosource: 'https://download.ourquraan.com/3bdullah_Khayyat/', title: "عبدالله خياط" },
    { id: 58, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/58.jpg', Audiosource: 'https://download.ourquraan.com/3bdallah-3wad-aljhny/',  title: "عبدالله عواد الجهني" },
    { id: 59, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/59.jpg', Audiosource: 'https://download.ourquraan.com/3bdallah_kamel/', title: "عبدالله كامل"  },
    { id: 60, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/60.jpg', Audiosource: 'https://download.ourquraan.com/3bdelmo7sen-el7arsy/', title: "عبدالمحسن الحارثي"},
    { id: 61, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/61.jpg', Audiosource: 'https://download.ourquraan.com/3bdulmohsin_Al-Obaikhan/',  title: "عبدالمحسن العبيكان" },
    { id: 62, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/62.jpg', Audiosource: 'https://download.ourquraan.com/3bdulmohsen_Alqasim/',title: "عبدالمحسن القاسم" },
    { id: 63, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/63.jpg', Audiosource: 'https://download.ourquraan.com/3bdalhady-ahmed-knakry/', title: "عبدالهادي أحمد كناكري" },
    { id: 64, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/64.png', Audiosource: 'https://download.ourquraan.com/3bdulwadood_Haneef/', title: "عبدالودود حنيف" },
    { id: 65, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/65.jpg', Audiosource: 'https://download.ourquraan.com/Othman_Al-Andary(Qalon)/', title: "عثمان الانداري" },
    { id: 66, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/66.jpg', Audiosource: 'https://download.ourquraan.com/3li_Alhuthaifi_(Qalon_An_Nafi)/',title: "علي الحذيفي" },
    { id: 67, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/67.jpg', Audiosource: 'https://download.ourquraan.com/3li-gaber/', title: "علي جابر"  },
    { id: 68, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/68.jpg', Audiosource: 'https://download.ourquraan.com/3li_Hajjaj_Alsouasi/', title: "علي حجاج السويسي"},
    { id: 69, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/69.jpg', Audiosource: 'https://download.ourquraan.com/3mad_Zuhair_Hafez/', title: "عماد زهير حافظ" },
    { id: 70, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/70.jpg', Audiosource: 'https://download.ourquraan.com/3mar_AlQazabri_(Warsh_An_Nafea)/', title: "عمر القزابري" },
    { id: 71, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/71.jpg', Audiosource: 'https://download.ourquraan.com/Fares_Abbad/', title: "فارس عباد"},
    { id: 72, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/72.jpg', Audiosource: 'https://download.ourquraan.com/Maher_Al-Muaiqly/', title: "ماهر المعيقلي" },
    { id: 73, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/73.jpg', Audiosource: 'https://download.ourquraan.com/Maher-shakhashero/', title: "ماهر شخاشيرو" },
    { id: 74, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/74.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Al-Abdullah_(Albizi_and_Qunbol_An_Ibn_Katheer)/', title: "محمد آل عبدالله" },
    { id: 75, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/75.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Al-Baraak/', title: "محمد البراك" },
    { id: 76, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/76.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Ayyub/', title: "محمد أيوب" },
    { id: 77, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/77.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Alafghani/', title: "محمد الأفغاني" },
    { id: 78, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/78.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Jibreel/', title: "محمد جبريل" },
    { id: 79, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/79.jpg', Audiosource: 'https://download.ourquraan.com/Muhammad_Hassan/', title: "محمد حسان" },
    { id: 80, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/80.jpg', Audiosource: 'https://download.ourquraan.com/Muhammed-Rashad-Alshrief/', title: "محمد رشاد الشريف" },
    { id: 81, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/81.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Saleh_Alim_Shah/', title: "محمد صالح عالم شاه" },
    { id: 82, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/82.jpg', Audiosource: 'https://download.ourquraan.com/Mohammed_Siddiq_Al-Minshawi/', title: "محمد صديق المنشاوي" },
    { id: 83, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/83.jpg', Audiosource: 'https://download.ourquraan.com/Muhammad_Aref_Al-Asali_Hafs_From_Aasem/', title: "محمد عارف العسلي" },
    { id: 84, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/84.jpg', Audiosource: 'https://server16.mp3quran.net/nourin_siddig/Rewayat-Aldori-A-n-Abi-Amr/', title: "محمد نورين صديق" },
    { id: 85, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/85.jpg', Audiosource: 'https://download.ourquraan.com/Mohammad_Abdulkareem/', title: "محمد عبدالكريم" },
    { id: 86, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/86.jpg', Audiosource: 'https://download.ourquraan.com/Mohd_Altablawi/', title: "محمد محمود الطبلاوي" },
    { id: 87, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/87.jpg', Audiosource: 'https://download.ourquraan.com/Mahmoud-Alrefa3y/', title: "محمود الرفاعي" },
    { id: 88, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/88.jpg', Audiosource: 'https://download.ourquraan.com/Mahmood_AlSheimy_(Dorai%20An%20Al-Kisai)/', title: "محمود الشيمي" },
    { id: 89, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/89.jpg', Audiosource: 'https://download.ourquraan.com/Mahmoud_Khalil_Al-Hussary/', title: "محمود خليل الحصري" },
    { id: 90, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/90.jpg', Audiosource: 'https://download.ourquraan.com/Mahmood_Ali_Albana_Mujawwad/', title: "محمود علي البنا" },
    { id: 91, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/91.jpg', Audiosource: 'https://download.ourquraan.com/Mishary_Alafasy/',title: "مشاري بن راشد العفاسي" },
    { id: 92, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/92.jpg', Audiosource: 'https://download.ourquraan.com/Mustafa_Ismail/', title: "مصطفى إسماعيل" },
    { id: 93, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/93.jpg', Audiosource: 'https://download.ourquraan.com/Mustafa_Al-Lahoni/', title: "مصطفى اللاهوني" },
    { id: 94, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/94.jpg', Audiosource: 'https://download.ourquraan.com/Mustafa_Raad_Al-Azawi/', title: "مصطفى رعد العزاوي" },
    { id: 95, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/95.jpg', Audiosource: 'https://download.ourquraan.com/M3ed-Al7arthy/', title: "معيض الحارثي" },
    { id: 96, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/96.jpg', Audiosource: 'https://download.ourquraan.com/Muftah_Alsaltany_(Hafs)/', title: "مفتاح السلطني" },
    { id: 97, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/97.jpg', Audiosource: 'https://download.ourquraan.com/Musa-Belal/', title: "موسى بلال" },
    { id: 98, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/98.jpg', Audiosource: 'https://download.ourquraan.com/Nasser_Al-Qatami/', title: "ناصر القطامي" },
    { id: 99, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/99.jpg', Audiosource: 'https://download.ourquraan.com/Nabil_Ar-Rifai/', title: "نبيل الرفاعي" },
    { id: 100, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/100.jpg', Audiosource: 'https://download.ourquraan.com/N3ma-Elhassan/', title: "نعمة الحسان" },
    { id: 101, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/101.jpg', Audiosource: 'https://download.ourquraan.com/Hani_Arrifai/', title: "هاني الرفاعي" },
    { id: 102, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/102.jpg', Audiosource: 'https://download.ourquraan.com/wadie_alyamni/', title: "وديع اليمني" },
    { id: 103, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/103.jpg', Audiosource: 'https://download.ourquraan.com/Waleed_Alnaehi_(Qalon-3n-nafe3)/', title: "وليد النائحي" },
    { id: 104, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/104.jpg', Audiosource: 'https://download.ourquraan.com/Yasser_Aldosari/',  title: "ياسر الدوسري" },
    { id: 105, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/105.jpg', Audiosource: 'https://download.ourquraan.com/Yaser-Alkershy/', title: "ياسر القرشي" },
    { id: 106, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/106.jpg', Audiosource: 'https://download.ourquraan.com/Yasser_Almazroyee_(ya3kooob)/', title: "ياسر المزروعي" },
    { id: 107, img: 'https://hassanaliabdelhamed.github.io/Quran-Picture/107.jpg', Audiosource: 'https://download.ourquraan.com/Yousef-Bin-Nooh-Ahmed/', title: "يوسف بن نوح أحمد"}
];

export default quraa;
